package com.cruxtrack.backend.user;

// CRUXTRACK: FIXED LIST OF ACCOUNT TYPES STORED IN THE DATABASE (ONE ROLE PER USER ROW)
// CRUXTRACK: YOU CAN ADD MORE VALUES LATER IF YOU NEED FINER PERMISSIONS (E.G. MANAGER)
public enum Role {
	// CRUXTRACK: NORMAL STAFF / GYM USER
	USER,
	// CRUXTRACK: CAN ACCESS /API/ADMIN/** URLS (SEE SECURITYCONFIG)
	ADMIN
}
